services:
  neuland-monitor:
    image: emacholdt/neuland-monitor:latest
    container_name: neuland-monitor
    restart: unless-stopped
    ports:
      - "8181:8181"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    # Optional: ensure it's in the same network as InfluxDB if running locally
    # networks:
    #   - monitoring

    # networks:
    #   monitoring:
    #     external: true
